#!/usr/bin/env bash

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
battery=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage:" | awk '{ print $2 }' | tr -d '%')
state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "state:" | awk '{ print $2 }')
lower_limit=20
upper_limit=96

if [ "$battery" -lt "$lower_limit" ]; then
    if [ "$state" != "charging" ]; then
        DISPLAY=:0 /usr/bin/notify-send --urgency=critical "Battery below 20%"
    fi
elif [ "$battery" -gt "$upper_limit" ]; then
    if [ "$state" == "charging" ]; then
        DISPLAY=:0 /usr/bin/notify-send --urgency=low "Charged up almost 100%"
    fi
fi
